Translate landing page + tweaks
Dsek-LTH/web pull request #360
Opened 2024-05-16 20:57 UTC by Isak-Kallini

Translated the landing page and made some tweaks. Most importantly I increased the padding on the sides on request from Dag (I also agree that it looks better both on the landing page and overall), this will affect the whole website.

2024-05-16 22:41 UTC, fnurkla requested changes
När jag har hållit på med `{en|sv}.json` så har jag tyckt att det var trevligt att ha de blanka raderna för att gruppera items. Därför ser jag gärna att de inte tas bort...

2024-05-17 06:12 UTC, Isak-Kallini commented
Ah, my bad, jag använde bara vscode pluginet så tänkte inte på hur det grupperades i filerna. Jag fixar 👍

2024-05-17 10:41 UTC, fnurkla approved these changes

2024-05-17 11:44 UTC, alfredgrip approved these changes

2024-05-17 12:34 UTC, merged