Add YouTube video support to articles.
Dsek-LTH/web pull request #623
Opened 2024-12-03 20:13 UTC by RufusKoggRojder

Fixes #479. 

Decided to go with embedding YouTube videos because I found that video hosting is very troublesome thanks to minio size limits.

Added [this dependency](https://www.npmjs.com/package/svelte-youtube-embed) for embedding.

2024-12-10 22:06 UTC, trilleplay requested changes

2024-12-10 22:06 UTC, trilleplay commented on src/routes/(app)/news/Article.svelte
> +  <Youtube id={article.youtubeUrl.split("=")[1]} />
just use an iframe

2024-12-10 22:06 UTC, trilleplay commented on src/routes/(app)/news/ArticleForm.svelte
> +    accept="video/*"
den ska inte accepta en `video/*` det är en sträng?

2024-12-10 22:20 UTC, Joel-Liden reviewed
looks reasonable, with Trille changes.

2024-12-11 13:52 UTC, RufusKoggRojder commented on src/routes/(app)/news/ArticleForm.svelte
> +    accept="video/*"
Tack, missade detta.

2024-12-11 14:56 UTC, RufusKoggRojder commented on src/routes/(app)/news/Article.svelte
> +  <Youtube id={article.youtubeUrl.split("=")[1]} />
Ok.

2024-12-30 11:42 UTC, merged